services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: pokedex_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  node_express:
    build:
      context: server/.
    container_name: server
    environment:
      NODE_ENV: development
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: mysecretpassword
      PG_DATABASE: pokedex_db
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./server:/app

  react:
    build:
      context: client/.
    container_name: client
    ports:
      - "5173:5173"
    depends_on:
      - postgres
      - node_express

volumes:
  postgres_data:
    driver: local
