services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: db-pokedex
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2urzDZ2w1dQM4wO
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  node_express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pokedex-app
    environment:
      NODE_ENV: production
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: 2urzDZ2w1dQM4wO
      PG_DATABASE: db-pokedex
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./server:/usr/src/app

volumes:
  postgres_data:
    driver: local
